export default {
    classic: {
        listViewBackgroundColor: '#f4f4f4',
        listViewBorderColor: '#DFDFDF',
        listViewEventBottomMargin: '0',
        listViewTextColor: '#3b3b3b',
        secondaryTextColor: '#5e5e5e',
        canvasBackgroundColor: '#fff',
        gridViewBackgroundColor: '#fff',
        gridViewBorderColor: '#ddd',
        secondaryBackgroundColor: '#f7f7f7',
        font: 'Open Sans',
        highlightColor: '#da4167'
    },
    nomad: {
        canvasBackgroundColor: '#fff',
        listViewBackgroundColor: '#fff',
        secondaryBackgroundColor: '#f5f5f5',
        highlightColor: '#ed564b',
        listViewTextColor: '#474747',
        secondaryTextColor: '#6f6f6f',
        listViewBorderColor: '#efefef',
        font: 'Nunito',
        listViewEventBottomMargin: '10',
        gridViewBorderColor: '#efefef',
        gridViewBackgroundColor: '#fff'
    },
    carrd: {
        listViewBackgroundColor: '#3f404c',
        listViewBorderColor: '#373742',
        listViewEventBottomMargin: '10',
        listViewTextColor: '#fff',
        secondaryTextColor: '#c8c8ca',
        canvasBackgroundColor: '#373742',
        gridViewBackgroundColor: '#3f404c',
        gridViewBorderColor: '#373742',
        secondaryBackgroundColor: '#30303b',
        font: 'Open Sans',
        highlightColor: '#57aba8'
    },
    stripe: {
        listViewBackgroundColor: '#fff',
        listViewBorderColor: '#f7f9fc',
        listViewEventBottomMargin: '10',
        listViewTextColor: '#3b485c',
        secondaryTextColor: '#6e7b91',
        canvasBackgroundColor: '#f7f9fc',
        gridViewBackgroundColor: '#fff',
        gridViewBorderColor: '#f6f6f6',
        secondaryBackgroundColor: '#fbfcfd',
        font: 'Montserrat',
        highlightColor: '#54b182'
    },
    ghost: {
        listViewBackgroundColor: '#283237',
        listViewBorderColor: '#232a2e',
        listViewEventBottomMargin: '10',
        listViewTextColor: '#d1d5d9',
        secondaryTextColor: '#acafb3',
        canvasBackgroundColor: '#232a2e',
        gridViewBackgroundColor: '#283237',
        gridViewBorderColor: '#232a2e',
        secondaryBackgroundColor: '#353f43',
        font: 'Montserrat',
        highlightColor: '#80c2ee'
    },
    intercom: {
        listViewBackgroundColor: '#fff',
        listViewBorderColor: '#fff',
        listViewEventBottomMargin: '10',
        listViewTextColor: '#000',
        secondaryTextColor: '#888',
        canvasBackgroundColor: '#fff',
        gridViewBackgroundColor: '#fff',
        gridViewBorderColor: '#eee',
        secondaryBackgroundColor: '#eee',
        font: 'Roboto',
        highlightColor: '#286EFA'
    }
}
